### PR TITLE
Fix annos

### LINKED ISSUE #36: More intelligently filter annotations during reparenting
After #35 The `ReParentCircuit` transform removes modules but doesn't smartly filter annotations (instead it just removes all `DontTouchAnnotation`s). Filtering on module name didn't seem to work for me.

### PR DESCRIPTION
**Pull request by colinschmidt**
Fixes #36 and other problems related to renaming annotations correctly

### CODE REVIEW

File: tapeout/src/main/scala/transforms/RemoveUnusedModules.scala [hunk 1]
```diff
@@ -53,17 +53,9 @@ class RemoveUnusedModules extends Transform {
     val renames = state.renames.getOrElse(RenameMap())
 
     // This is what the annotation filter should look like, but for some reason it doesn't work.
```
Comment (jwright6323) [inline tapeout/src/main/scala/transforms/RemoveUnusedModules.scala]: This comment can die now :)

**Comment by jwright6323** [comment]
LGTM, @azidar should probably take a look too
